# Generated by Django 4.2.3 on 2023-08-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advert',
            table='advertisements',
        ),
    ]
