# Generated by Django 4.2.3 on 2023-09-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='Djando_projango/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
